# Generated by Django 4.2.6 on 2023-11-02 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github_analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributordata',
            name='contributor',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='user_profile',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
