# Generated by Django 4.2.6 on 2023-11-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_analytics', '0002_remove_contributordata_contributor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitdata',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
