# Generated by Django 4.2.6 on 2023-11-03 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('github_analytics', '0003_alter_commitdata_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_username', models.CharField(max_length=255, unique=True)),
                ('avatar_url', models.URLField(blank=True, max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='contributordata',
            name='contributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='github_analytics.userprofile'),
        ),
    ]
