# Generated by Django 4.2.6 on 2023-11-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_analytics', '0004_userprofile_contributordata_contributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitdata',
            name='date',
            field=models.DateField(),
        ),
    ]
