# Generated by Django 4.2.6 on 2023-11-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_analytics', '0005_alter_commitdata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitdata',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
