# Generated by Django 4.2.6 on 2023-11-10 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github_analytics', '0006_alter_commitdata_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commitdata',
            name='commit_count',
        ),
    ]
