# Generated by Django 4.2.6 on 2023-11-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_analytics', '0009_alter_commitdata_repository_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullrequestdata',
            name='date_created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pullrequestdata',
            name='date_merged',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
